name: GCP Deployment

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.96.0'
          extended: true

      - name: Build
        run: make init; make build

      - name: GCP Auth
        uses: google-github-actions/auth@v0
        with:
          # workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          # service_account: 'my-service-account@my-project.iam.gserviceaccount.com'
          credentials_json: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}

      # - name: Sync Website to Google Cloud Storage
      #   uses: 'google-github-actions/upload-cloud-storage@v0'
      #   with:
      #     path: public
      #     destination: creations.kgol.xyz
      #     parent: false
